export enum MataPelajaranEnum {
    SOSIOLOGI = "Sosiologi",
    BAHASA_INDONESIA = "Bahasa Indonesia",
    BAHASA_INGGRIS = "Bahasa Inggris",
    PPKN = "Pendidikan Pancasila",
    SEJARAH = "Sejarah",
    BIOLOGI = "Biologi",
    FISIKA = "Fisika",
    KIMIA = "Kimia",
    MATEMATIKA_TINGKAT_LANJUT = "Matematika tingkat lanjut",
    EKONOMI = "Ekonomi",
    GEOGRAFI = "Geografi",
    EKONOMI_DAN_MATEMATIKA = "Ekonomi dan/atau Matematika",
    GEOGRAFI_DAN_MATEMATIKA = "Geografi dan/atau Matematika",
    SOSIOLOGI_DAN_MATEMATIKA = "Sosiologi dan/atau Matematika",
    SOSIOLOGI_DAN_PPKN = "Sosiologi dan/atau Pendidikan Pancasila",
    BIOLOGI_DAN_KIMIA = "Biologi dan/atau Kimia",
    MATEMATIKA_DAN_FISIKA = "Matematika dan/atau Fisika",
    PJOK = "Pendidikan Jasmani Olahraga, dan Kesehatan (PJOK)",
}
