export enum MataPelajaranEnum {
    SOSIOLOGI = "Sosiologi",
    BAHASA_INDONESIA = "Bahasa Indonesia",
    BAHASA_INGGRIS = "Bahasa Inggris",
    PPKN = "Pendidikan Pancasila",
    SEJARAH = "Sejarah",
    BIOLOGI = "Biologi",
    FISIKA = "Fisika",
    KIMIA = "Kimia",
    MATEMATIKA = "Matematika",
    MATEMATIKA_TINGKAT_LANJUT = "Matematika tingkat lanjut",
    EKONOMI = "Ekonomi",
    GEOGRAFI = "Geografi",
    PJOK = "Pendidikan Jasmani Olahraga, dan Kesehatan (PJOK)",
}
